version: '2.0'

services:
  app:
    ports:
      - 4040:4040
    build: ./
    image: mean
    hostname: "app"
    expose:
      - 4040
    environment:
      NODE_ENV: production
      SERVER_PORT: 4040
      JWT_SECRET: 0a6b944d-d2fb-46fc-a85e-0295c986cd9f
      MONGO_HOST: mongodb://mongo/odmp
    restart: always
    depends_on:
      - mongo
      - filebeat
      - logstash
    volumes:
      - app_logs:/usr/src/app/server/config/log/
  mongo:
    image: mongo:3.6
    hostname: "mongo"
  logstash:
    image: docker.elastic.co/logstash/logstash:7.0.0
    hostname: "logstash"
    ports:
      - 5044:5044
      - 5054:5054
    volumes:
      - ./dockerconf/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./dockerconf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - ELASTICSEARCH_HOSTS=https://5fe2eae3c9cc4862939470ff33d86445.us-east-1.aws.found.io:9243
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=O10PLFJ9rrDD1dNImx4eiZPq
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.0.0
    hostname: "filebeat"
    user: root
    depends_on:
      - logstash
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers
      - app_logs:/var/log/app
      - ./dockerconf/filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: ["--strict.perms=false"]
volumes:
  app_logs: